AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.3
  Exclude:
    - 'vendor/bundle/**/*'
    - '**/db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'

Style/Documentation:
  Enabled: false
