version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: .
    env_file: .env
    command: 'entrypoints/docker-entrypoint.sh'
    depends_on:
      - db
    volumes:
      - .:/app
