version: '3'
services:
  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: .
    tty: true
    stdin_open: true
    env_file: .env
    command: 'ruby bin/bot.rb'
    depends_on:
      - db
    volumes:
      - .:/app
