version: '3'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: .
    command: 'ruby entrypoint.rb'
    depends_on:
      - db
