version: '3'
services:
  db:
    image: mysql:8.0
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./tmp/db:/var/lib/mysql
  app:
    build: .
    tty: true
    stdin_open: true
    env_file: .env
    command: 'ruby bin/bot.rb'
    depends_on:
      - db
    volumes:
      - .:/app
