name: Rspec

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 3.1.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true
      - name: Install gems
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
